### ISSUE TITLE
Accepteer taken is in productie (nexxus.eco) Order status ingepland

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/Nexxus-App#110]
Dit moet zijn to plan en pick up lijkt mij.

**Comment by nebbii** [comment]
Aangeboden taken zijn hardcoded als Status ID 2 en Geaccepteerde taken als Status ID 300. Het was ontworpen dat de Nexxus manager hier rekening mee zou houden en de status ID zou aanpassen aan de App.
