### ISSUE TITLE
De geaccepteerde taken is in de productie omgeving Order status bezorgd+vernietigingsverklaring.

### ISSUE THREAD

**Issue by ronalddebakker** [Nexxus/Nexxus-App#111]
Dit moet zijn order status Order ingepland, lijkt mij.

**Comment by nebbii** [comment]
@ronalddebakker Dit is hardcoded als Status ID 300. Het was ontworpen dat de Nexxus manager hier rekening mee zou houden en de status ID zou aanpassen aan de App.
